import Footer from '@/components/footer';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.scss';
import Header from '@/components/header';
import { Noto_Sans_KR } from 'next/font/google';
import { SWRConfig } from 'swr';

const inter = Inter({ subsets: ['latin'] });
const notoSansKr = Noto_Sans_KR({
  subsets: ['latin'],
  weight: ['100', '400', '700', '900'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`${notoSansKr.className}`}>
      <body>
        <Header />
        {children}
        <div id="modal-root" />
        <Footer />
      </body>
    </html>
  );
}
